title: Edgar Huynh
description: Personal Website
theme: jekyll-theme-tactile

# Navigation items for smooth scrolling
navigation:
  - title: About
    url: "#about"
  - title: Skills
    url: "#skills"
  - title: Projects
    url: "#projects"
  - title: Experience
    url: "#experience"
  - title: Contact
    url: "#contact"
